import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Flex, Text, Button, DarkMode, Heading } from '@chakra-ui/react';
import { CheckCircleIcon } from '@chakra-ui/icons';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Flex
          direction='column'
          bgColor='gray.900'
          textColor='white'
          rounded='3xl'
          padding='10'
        >
          <Heading display='flex' alignItems='center'>
            Next.js + Chakra UI{' '}
            <CheckCircleIcon marginLeft='8' color='twitter.400' />
          </Heading>
          <Text fontSize='2xl' fontWeight='bold' marginTop='8' marginBottom='8'>
            This project is bootstrapped with Chakra UI
          </Text>
          <DarkMode>
            <Button>Start creating beautiful experience</Button>
          </DarkMode>
        </Flex>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
